// <auto-generated />
namespace TwentyFour.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CrossedFingers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrossedFingers));
        
        string IMigrationMetadata.Id
        {
            get { return "202106020206360_CrossedFingers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
